/*
class ExceptionByDurga1
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("Hello");  // O/P: Hello
		}
		catch(ArithmeticException ae)
		{
			
		}
	}
}


class ExceptionByDurga2
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("Hello");    //O/P: Hello
		}
		catch(Exception e)
		{
			
		}
	}
}


import java.io.*;
class ExceptionByDurga3
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("Hello");
		}
		catch(java.io.IOException ioe) //CE:
		{
			
		}
	}
}


class ExceptionByDurga3
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("Hello");
		}
		catch(NullPointerException npe)   // O/P:Hello
		{
			
		}
	}
}



class ExceptionByDurga3
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("Hello");
		}
		catch(InterruptedException ie)   //   CE
		{
			
		}
	}
}
*/


class ExceptionByDurga4
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("Hello");   //O/P: Hello
		}
		catch(Error e)
		{
			
		}
	}
}